### ISSUE TITLE
password from password-file not working if it has spaces at the end

### ISSUE THREAD

**Issue by Schweber** [rustic-rs/rustic#1099] opened 2024-03-11 13:44 UTC
I tried 
```
[repository]
password-file = "/path/to/file.txt"
```
The file just contains `"password  "` (2 spaces after password) but rustic tells me that the password is not correct. If i use
```
[repository]
password = "password  "
```
it works fine (also 2 spaces after password). It appears to me that the spaces at the end are not properly recognized. 

Can you reproduce this?

**Comment by aawsome** [comment] 2024-03-11 20:08
@Schweber Thanks for opening the issue! Unfortunately I cannot reproduce the issue. If put "test  " in the password file it works exactly like putting it in the config profile or using `--password "test  "`.

The logic of reading the password from the file is very simple:
- read the whole file
- if it ends with "\r\n" (windows newline), remove that newline and use the remaining as password.
- if it ends with "\n" (unix newline), remove that newline and use the remaining as password.
- else use the complete content as password

What does your password file exactly contain? `"password  "` (including the `"`)? In this case, you have to remove the `"`.
Or could it be that your `file.txt` contains a newline followed by the spaces?

**Comment by aawsome** [comment] 2024-03-12 20:21
Mhh - could be that there was some unprintable character at the end which you removed by inserting and removing the newline...
Anyway, as it seems there is nothing to reproduce, so I'm closing this issue.
Feel free to open again if you discover something new!

**Closed by aawsome** 2024-03-12 20:21 UTC
Labels: C-question
