### ISSUE TITLE
`restore`: dealing with long paths in an OS-"agnostic" way

### ISSUE THREAD

**Issue by ss256100** [rustic-rs/rustic#1101] opened 2024-03-12 13:35 UTC
Hello [username] Im poor sysadmin from Australia and I just patiently asking about adding some simple feature in such great tool as rustic is. Pls anyone: if u have time: make kinda fixer-function in rustic which will handle nonecomaptable-paths on *nix and Windows. Nowadays rustic and restic in 90% cases cant restore data on Windows if it was taken Linux

**Comment by kapitainsky** [comment] 2024-03-12 14:51
Could you provide some example to make it more clear what the issue is ? I run and restore backups between macOS/Linux/Windows and never experienced problem which would require some "normalisation" functionality.

**Comment by ss256100** [comment] 2024-03-15 19:08
Sure. The problem exist then paths longs then allowed by OS.

On Linux-based operating systems, a path can be up to 4,096 characters long. On Windows operating systems, the maximum path length can be up to 260 characters (also known as MAX_PATH) by default. However, Windows 10 allows users to use longer path lengths of up to 32,767 characters by enabling the "Long Paths" group policy. 

Restrictions is very different so need to check it before start restoration process. 
Thx for fast replay. A very big thx for taking care about so brilliant tool.

Have a nice day!

**Comment by kapitainsky** [comment] 2024-03-15 19:13
I am not sure how kopia could help here... if you work in multi OS environment it is your responsibility to plan accordingly. The same could be be said about other aspects e.g. case sensitivity - one filesystem is case sensitive but other is not.

**Comment by aawsome** [comment] 2024-03-15 19:15
@ss256100 Sorry, I didn't really get which feature you are requesting. 

Can you give an example what you try to do, which rustic command(s) you call and what the output is (and maybe what you expect rustic to do instead)?

About restoring and paths longer than allowed by the OS: This is not a problem rustic can solve. But do you know rustic's possibility to restore sub-paths?  
e.g. like `rustic restore a623b8:/my/long/path/in/snaapshot/dir /localdir/`?

**Comment by aawsome** [comment] 2024-03-27 05:34
@ss256100 Can you please provide any more information? If it is just about too long paths, I'm going to close this issue as it is out of rustic's hands...

**Comment by aawsome** [comment] 2024-04-22 20:42
closing this issue as there is nothing rustic can do.

**Closed by aawsome** 2024-04-22 20:42 UTC
Labels: C-question, A-commands, A-ui-ux, A-filesystem
