### ISSUE TITLE
No support for ssh, sftp, scp or secure transports

### ISSUE THREAD

**Issue by desrod** [rustic-rs/rustic#441] opened 2023-02-23 03:44 UTC
Obviously a pretty big one, but why are SSH, SFTP, SCP not supported backends for rustic?

**Comment by aawsome** [comment] 2023-02-23 05:52
Thanks for opening this issue.

About SFTP: This is a duplicate of #389 (and SFTP actually is supported via rclone)

About SSH: This is no backend. rustic needs a storage backend where it can store and read files and list directories. SSH is a remote shell which of course can also be used as transport layer for a file transfer protocol, but then we are at SFTP.

About SCP: Here the functionality of listing directories is missing.

About secure transports in general: The REST backend supports accessing a REST server via https. Here are two use-cases:
- run the [REST server](https://github.com/restic/rest-server) an a remote storage server and access it via `--repository rest:https://<server>:port`. There is also https://github.com/aawsome/rust-server.
- run `rclone serve restic` which can expose the REST api to a remote client running rustic/restic. This use-case is especially interesting when using the `--append-only` option of `rclone`.

**Comment by aawsome** [comment] 2023-02-26 05:43
IMO this boils down to SFTP support and therefore is a duplicate of #389.
I'm closing this issue - feel free to reopen if there is an aspect I didn't see!

**Closed by aawsome** 2023-02-26 05:43 UTC
Labels: duplicate
