### ISSUE TITLE
`find`: design and implement a command for finding files in snapshots

### ISSUE THREAD

**Issue by n8henrie** [rustic-rs/rustic#1055] opened 2024-02-07 14:16 UTC
According to https://rustic.cli.rs/docs/comparison-restic.html I see the `find` and `mount` commands are missing.

I see an existing issue for [`mount`](https://github.com/rustic-rs/rustic/issues/971).

Is there any ongoing work or major blockers for the `find` command? I haven't used `mount`, but I've used [restic's `find` command](https://restic.readthedocs.io/en/stable/075_scripting.html#find) frequently.

**Comment by aawsome** [comment] 2024-02-07 22:28
Thanks @n8henrie for opening this issue!

Can you give some use cases where you are using `find`?

In fact, implementing it like it's done in restic would be very straightforward. The reason it isn't yet done is because I didn't simply want to reproduce what restic is doing, but wanted to have a much more featureful command which
- can show history of files
- can find identical files throughout the repository
- is speed-optimized by being able to skip some subtrees in certain search-scenarios
...

But there is also nothing wrong with starting with a simple re-implementation! If you give more input, I can work on it or mentor anyone who is willing to start a PR!

**Comment by n8henrie** [comment] 2024-02-07 22:54
That's awesome! I'm AFK on mobile but will get back with an example soon, and I'd love to work on a PR with some mentorship!

I've been keeping an eye on Rustic specifically because I enjoy writing rust much more than go, but I'm definitely still a novice.

**Comment by aawsome** [comment] 2024-02-25 19:07
@n8henrie Are you still interested?

**Comment by n8henrie** [comment] 2024-02-25 19:45
Yes I am! But I'm very busy with a few projects right now, will likely have some time in about a week.

If you'd like to close to keep the issue tracker groomed, I can bookmark this and prompt to reopen once I have time. Otherwise, if it's okay to leave open that's also fine of course.

Thanks for the nudge!

**Comment by n8henrie** [comment] 2024-03-22 14:07
Sorry this is taking so long, I am excited about the opportunity to contribute and especially the mentorship!

> Can you give some use cases where you are using find?

I've used it multiple times to find snapshot IDs that contain a specific file of interest. For example, if I discover that I have inadvertently deleted or corrupted a file locally, but I'm not sure when that modification occurred, I may first `restic find` the file in question, then examine the resulting snapshots to help determine from which snapshot I should restore.

For example, I have a wrapper script called `restic-cmd.sh` that presets a few restic parameters based on hostname and prefills in my nas (where the restic repo sits):

```
sudo -u restic /backup/restic/bin/restic --repo /backup/restic/backup/linux find restic-cmd.sh
repository a4458c04 opened (repository version 2) successfully, password is correct
Found matching entries in snapshot 9df7ed13 from 2020-04-30 02:00:13
/home/n8henrie/git/restic-backup/restic-cmd.sh

Found matching entries in snapshot 6520434a from 2020-05-31 02:00:07
/home/n8henrie/git/restic-backup/restic-cmd.sh

Found matching entries in snapshot daad20e3 from 2018-11-30 02:00:29
/home/n8henrie/git/restic-backup/restic-cmd.sh

Found matching entries in snapshot 367be981 from 2020-03-31 02:00:13
/home/n8henrie/git/restic-backup/restic-cmd.sh

Found matching entries in snapshot bed5561e from 2019-08-31 02:00:41
/home/n8henrie/git/restic-backup/restic-cmd.sh
...
```

Searching my shell history, I've also used it in the past to:

- restore ssh private keys that I deleted (whups!) but thankfully had backed up
- look for evidence of files being backed up that I had hoped to exclude
- look for evidence of files being backed up that I was afraid were being blocked by MacOS security / privacy permissions

For my future reference, it looks like this is the implementation in restic: https://github.com/restic/restic/blob/d1d773cfcd3115aecbbd6ad6be2bc5e11f395b29/cmd/restic/cmd_find.go#L77

**Comment by aawsome** [comment] 2024-03-22 18:52
@n8henrie Great that you are about to start - and no worry, we all work in our free time so delays from time to time are pretty common...

Do you have a Discord account? If we want to chat something more detailed, it might be a possibility to open a channel there.

Now, about your use-case: I think we actually have two use-cases:
- find a file in the snapshots where the full path is known, e.g. `/home/n8henrie/git/restic-backup/restic-cmd.sh`
- find all files in the snapshots which match some criteria like filename `restic-cmd.sh`. This could be extended in future by using wildcards / regular expressions etc. but could be also about metadata like "files greater than 50MiB" or "owned by user xyz". And maybe possibility to combine matching conditions....

I would suggest to you to start implementing one of those using just a simple traversal.

 If you look at https://github.com/rustic-rs/rustic/blob/main/src/commands/snapshots.rs you see can how you can get the (already grouped) snapshots list and how to iterate over it (using a simple "for" loop is sufficient actually). 

Now, if you already have a snapshot, take a look at https://github.com/rustic-rs/rustic/blob/main/src/commands/ls.rs which uses `Repository.ls` to traverse a given tree - this can of course also be the whole snapshot. It returns path and all metadata, so you can use that to decide if an entry matches or not and then print it.

Hope this helps for a start, but please don't hesitate to ask if you need any more details about one point!

**Comment by aawsome** [comment] 2024-03-22 19:07
Just some comments why I think the first one is a different use case:

When we are searching for a given full path, we know that this can only be zero or exactly one match per repository. This allows things like showing not only all "matching" snapshots, but also a more detailed history of this full path (like when did metadata change or when did the content change). Also we can heavily optimize here: if there is no `home` tree in a snapshot you can directly skip it without needing to traverse all trees.

**Comment by aawsome** [comment] 2024-04-30 19:52
closing this as it has been implemented in #1136

**Closed by aawsome** 2024-04-30 19:52 UTC
Labels: C-enhancement, A-cli, A-commands, A-ui-ux

**Comment by n8henrie** [comment] 2024-04-30 21:25
Thank you! As mentioned I'll look for other opportunities to contribute.

**Comment by aawsome** [comment] 2024-04-30 21:28
@n8henrie Thanks a lot for your offer! An easy way to start with small contributions (besides opening issues which is also warmly welcome!) is to improve the docu: https://github.com/rustic-rs/docs
