### ISSUE TITLE
Parity with restic arguments?

### ISSUE THREAD

**Issue by Ineluki** [rustic-rs/rustic#625] opened 2023-04-30 19:09 UTC
I've noticed some commands don't work the same way as they do in restic. 

Examples:

`--json` missing on: repoinfo, forget

`--iexclude` missing on backup

`stats` has been renamed to `repoinfo` (?)

Is it intended for these gaps to be fixed eventually? It would make it a lot easier to use as a drop-in replacement.

**Comment by aawsome** [comment] 2023-04-30 19:23
CLI compatibility is not intended.
See also #540 (I think this issue is a duplicate of this).

About missing `--json` options : Can you open separate issues?
About `--iexclude`: You can get this functionality use `--iglob` with negative patterns (prefix them by `!`).
About `stats` vs `repoinfo`: These commands are actually very different an cannot be compared. Try out `rustic repoinfo` and look at the information `rustic snapshots` gives you, especially using the `--long` or `--json` options. If you are still missing any information, please open an issue.

**Comment by Ineluki** [comment] 2023-05-01 06:53
Good to know, thanks. I was using an outdated version, but will create new tickets for each missing `--json` I find.

As for `--iglob` it still gives me an error. Am I missing something obvious?

Args are:

```
[
    "--iglob=!/home/ineluki/Codez/int/restic-ui3/data/repo",
    "--json",
    "backup",
    "--exclude-caches",
    "--tag=/home/ineluki/Videos/animals",
    "-r=/home/ineluki/Codez/int/restic-ui3/data/repo",
    "/home/ineluki/Videos/animals"
]
```

stderr is:
```
error: unexpected argument '--iglob' found
tip: 'backup --iglob' exists
```

**Comment by aawsome** [comment] 2023-05-01 09:19
--iglob is only available for the backup comnand and must therefore come after backup. Same with --json. Only global options can come before vor after the comnand.

**Comment by aawsome** [comment] 2023-05-03 11:47
After the two missing `--json` options are now separate issues, I'm closing this as duplicate of #540.

**Closed by aawsome** 2023-05-03 11:47 UTC
Labels: duplicate
