### ISSUE TITLE
Allow the use of `~` in the config file.

### ISSUE THREAD

**Issue by kamack38** [rustic-rs/rustic#1354] opened 2024-11-15 15:26 UTC
Hi, currently, rustic doesn't allow the use of environment variables or `~` in the sources in the config file. I'd really like to use my `$HOME` var or `~` to specify the file path, so I don't have to write the whole file path every time. This feature would also allow me to use the same rustic config file across multiple users (with different usernames).

**Comment by simonsan** [comment] 2024-11-15 16:34
Duplicate of #996

**Closed by simonsan** 2024-11-15 16:34 UTC
Labels: S-triage
