### ISSUE TITLE
[Windows] Non-unicode filenames issue

### ISSUE THREAD

**Issue by parasiteoflife** [rustic-rs/rustic#517] opened 2023-03-23 00:38 UTC
I created some files to test rustic on Windows. These are the names I picked:

```
± × ÷ √≠ ≤ ≥ ≡← → ⇒∴ ∵¦ ¬ ⋄° ∞ ‰µ ∅.txt
« »‹ ›“ ”‘ ’‚ „〞〝.txt
©®℠™₥¢¤€£₡¥₦₨₩฿₫₠₣₤₧₢.txt
♩ ♪ ♫ ♬ ♭ ♮ ♯.txt
½⅓¼⅕⅙⅐⅛⅑ ⅔⅖ ¾⅗ ⅘ ⅚⅝ ⅞.txt
Ą Ç Ḑ Ȩ Ģ Ḩ Ķ Ļ Ņ Ŗ Ş Ţ.txt
Ǎ Ě Ǐ Ǒ Ǔ Č Ď Ǧ Ȟ ǰ Ǩ Ľ Ň Ř Š Ť Ž.txt
Ă Ĕ Ĭ Ŏ Ŭ Ğ.txt
Â Ê Î Ô Û Ŷ Ĉ Ĝ Ĥ Ĵ Ŝ Ŵ Ẑ.txt
Á É Í Ó Ú Ý Ć Ǵ Ḱ Ĺ Ḿ Ń Ṕ Ŕ Ś Ẃ Ź.txt
Ā Ē Ī Ō Ū Ȳ Ḡ.txt
Ä Ë Ï Ö Ü Ÿ Ḧ Ẅ Ẍ ẗ.txt
À È Ì Ò Ù Ỳ Ǹ Ẁ.txt
Ã Ẽ Ĩ Õ Ũ Ỹ Ñ Ṽ.txt
Ą Ę Į Ǫ Ų.txt
Å Ů ẘ ẙ.txt
ÁáÉéÍí テスト ÓóÚúÑñ.txt
ÁáÉéÍíÓóÚúÑñ.txt
Æ æ.txt
ⁱ ⁿ ª ºʰ ʲ ˡ ʳ ˢ ʷ ˣ ʸ⁰ ¹ ² ³ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹⁽ ⁺ ⁼ ⁾₍ ₊ ₌ ₎₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉.txt
Ɨ Ø ƀ Đ Ǥ Ħ Ł Ŧ Ƶ.txt
Ő Ű.txt
ǖ ǘ ǚ ǜ.txt
テスト.txt
```

I think these include some common non-unicode characters.  
I proceeded to create snapshots with restic and rustic.

Rustic backup the directory without any problems, listing the files also shows all the files and the characters except for a few but that's most probably because of Windows' CMD because the output is exactly the same as the one restic does.

Now the problem comes when trying to restore the files:

- Restoring using rustic only restores 3 files: `ÁáÉéÍí テスト ÓóÚúÑñ.txt`, `ÁáÉéÍíÓóÚúÑñ.txt`, `テスト.txt`.
- Restoring using restic restores all the 24 files.
- Restoring the rustic-created snapshot using restic also restores all the 24 files.

debug-log:

```
00:26:00 [INFO] repository C:\rustic: password is correct.
00:26:00 [INFO] using cache at C:\Users\parasiteoflife\AppData\Local\rustic\483ac73ceee10cb243a346ced17c7e945f3127dd47873cce0e77e5c68e7e6430
00:26:00 [INFO] getting snapshot...
00:26:00 [DEBUG] (1) rustic::commands::restore: to restore: "test_dir"
00:26:00 [DEBUG] (1) rustic::commands::restore: to restore: "test_dir\\ÁáÉéÍí テスト ÓóÚúÑñ.txt"
00:26:00 [DEBUG] (1) rustic::commands::restore: to restore: "test_dir\\ÁáÉéÍíÓóÚúÑñ.txt"
00:26:00 [DEBUG] (1) rustic::commands::restore: to restore: "test_dir\\テスト.txt"
00:26:00 [INFO] total restore size: 68 B
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\©®℠™₥¢¤€£₡¥₦₨₩฿₫₠₣₤₧₢.txt"
00:26:00 [WARN] restore "test_dir\\©®℠™₥¢¤€£₡¥₦₨₩฿₫₠₣₤₧₢.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\« »‹ ›“ ”‘ ’‚ „〞〝.txt"
00:26:00 [WARN] restore "test_dir\\« »‹ ›“ ”‘ ’‚ „〞〝.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\± × ÷ √≠ ≤ ≥ ≡← → ⇒∴ ∵¦ ¬ ⋄° ∞ ‰µ ∅.txt"
00:26:00 [WARN] restore "test_dir\\± × ÷ √≠ ≤ ≥ ≡← → ⇒∴ ∵¦ ¬ ⋄° ∞ ‰µ ∅.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\½⅓¼⅕⅙⅐⅛⅑ ⅔⅖ ¾⅗ ⅘ ⅚⅝ ⅞.txt"
00:26:00 [WARN] restore "test_dir\\½⅓¼⅕⅙⅐⅛⅑ ⅔⅖ ¾⅗ ⅘ ⅚⅝ ⅞.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\À È Ì Ò Ù Ỳ Ǹ Ẁ.txt"
00:26:00 [WARN] restore "test_dir\\À È Ì Ò Ù Ỳ Ǹ Ẁ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Á É Í Ó Ú Ý Ć Ǵ Ḱ Ĺ Ḿ Ń Ṕ Ŕ Ś Ẃ Ź.txt"
00:26:00 [WARN] restore "test_dir\\Á É Í Ó Ú Ý Ć Ǵ Ḱ Ĺ Ḿ Ń Ṕ Ŕ Ś Ẃ Ź.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\ÁáÉéÍí テスト ÓóÚúÑñ.txt"
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\ÁáÉéÍíÓóÚúÑñ.txt"
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Â Ê Î Ô Û Ŷ Ĉ Ĝ Ĥ Ĵ Ŝ Ŵ Ẑ.txt"
00:26:00 [WARN] restore "test_dir\\Â Ê Î Ô Û Ŷ Ĉ Ĝ Ĥ Ĵ Ŝ Ŵ Ẑ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ã Ẽ Ĩ Õ Ũ Ỹ Ñ Ṽ.txt"
00:26:00 [WARN] restore "test_dir\\Ã Ẽ Ĩ Õ Ũ Ỹ Ñ Ṽ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ä Ë Ï Ö Ü Ÿ Ḧ Ẅ Ẍ ẗ.txt"
00:26:00 [WARN] restore "test_dir\\Ä Ë Ï Ö Ü Ÿ Ḧ Ẅ Ẍ ẗ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Å Ů ẘ ẙ.txt"
00:26:00 [WARN] restore "test_dir\\Å Ů ẘ ẙ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Æ æ.txt"
00:26:00 [WARN] restore "test_dir\\Æ æ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ā Ē Ī Ō Ū Ȳ Ḡ.txt"
00:26:00 [WARN] restore "test_dir\\Ā Ē Ī Ō Ū Ȳ Ḡ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ă Ĕ Ĭ Ŏ Ŭ Ğ.txt"
00:26:00 [WARN] restore "test_dir\\Ă Ĕ Ĭ Ŏ Ŭ Ğ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ą Ç Ḑ Ȩ Ģ Ḩ Ķ Ļ Ņ Ŗ Ş Ţ.txt"
00:26:00 [WARN] restore "test_dir\\Ą Ç Ḑ Ȩ Ģ Ḩ Ķ Ļ Ņ Ŗ Ş Ţ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ą Ę Į Ǫ Ų.txt"
00:26:00 [WARN] restore "test_dir\\Ą Ę Į Ǫ Ų.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ő Ű.txt"
00:26:00 [WARN] restore "test_dir\\Ő Ű.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ɨ Ø ƀ Đ Ǥ Ħ Ł Ŧ Ƶ.txt"
00:26:00 [WARN] restore "test_dir\\Ɨ Ø ƀ Đ Ǥ Ħ Ł Ŧ Ƶ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\Ǎ Ě Ǐ Ǒ Ǔ Č Ď Ǧ Ȟ ǰ Ǩ Ľ Ň Ř Š Ť Ž.txt"
00:26:00 [WARN] restore "test_dir\\Ǎ Ě Ǐ Ǒ Ǔ Č Ď Ǧ Ȟ ǰ Ǩ Ľ Ň Ř Š Ť Ž.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\ǖ ǘ ǚ ǜ.txt"
00:26:00 [WARN] restore "test_dir\\ǖ ǘ ǚ ǜ.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\ⁱ ⁿ ª ºʰ ʲ ˡ ʳ ˢ ʷ ˣ ʸ⁰ ¹ ² ³ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹⁽ ⁺ ⁼ ⁾₍ ₊ ₌ ₎₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉.txt"
00:26:00 [WARN] restore "test_dir\\ⁱ ⁿ ª ºʰ ʲ ˡ ʳ ˢ ʷ ˣ ʸ⁰ ¹ ² ³ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹⁽ ⁺ ⁼ ⁾₍ ₊ ₌ ₎₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\♩ ♪ ♫ ♬ ♭ ♮ ♯.txt"
00:26:00 [WARN] restore "test_dir\\♩ ♪ ♫ ♬ ♭ ♮ ♯.txt": setting file times failed.
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir\\テスト.txt"
00:26:00 [DEBUG] (1) rustic::commands::restore: setting metadata for "test_dir"
00:26:00 [INFO] restore done.
```

**Comment by aawsome** [comment] 2023-03-23 06:48
Thanks a lot for the tests!
I have to say that all filenames seem to be valid unicode for me. And the fact that restic is able to restore seems to show that rustic creates a valid snapshot for your examples.

About the restore problem: Could it be that some of your files have a zero size? Then this is because of #519

**Comment by aawsome** [comment] 2023-03-23 11:44
#519 is now fixed in the latest beta build. Can you redo your tests?

**Comment by aawsome** [comment] 2023-03-24 05:19
Closing this as duplicate of #519

**Closed by aawsome** 2023-03-24 05:19 UTC

**Comment by aawsome** [comment] 2023-03-28 05:00
@parasiteoflife Thanks a lot for reporting!

Can you please give the error message/output of the `restore` command? Thanks!

**Comment by aawsome** [comment] 2023-03-30 05:41
Can you please open a new issue about this restore problem?  I don't know if this is really a filename topic, could be more about path handling on windows...

As this issue here is already closed, I might accidentially oversee it..
