### ISSUE TITLE
Exit with non-zero exit code in case of storage failure

### ISSUE THREAD

**Issue by rdelaage** [rustic-rs/rustic#1183] opened 2024-07-29 08:33 UTC
Hello,

I am using rustic in a backup script. I would like to be able to send notifications by email in case of errors during the process. I realized that in case of storage failure, rustic do not report the error using a non-zero exit code. For example
```
$ rustic check
[INFO] using config /etc/rustic/rustic.toml
[WARN] operation=stat path=config -> retry after 1.1497064830000001s: error=Unexpected (temporary) at stat, context: { url: http://10.245.25.7/mail.delaage.fr-backups/config, called: http_util::Client::send, service: s3, path: config } => send http request, source: error sending request for url (http://10.245.25.7/mail.delaage.fr-backups/config): error trying to connect: tcp connect error: No route to host (os error 113)
[WARN] operation=stat path=config -> retry after 2.141488671s: error=Unexpected (temporary) at stat, context: { url: http://10.245.25.7/mail.delaage.fr-backups/config, called: http_util::Client::send, service: s3, path: config } => send http request, source: error sending request for url (http://10.245.25.7/mail.delaage.fr-backups/config): error trying to connect: tcp connect error: No route to host (os error 113)
[WARN] operation=stat path=config -> retry after 4.00917232s: error=Unexpected (temporary) at stat, context: { url: http://10.245.25.7/mail.delaage.fr-backups/config, called: http_util::Client::send, service: s3, path: config } => send http request, source: error sending request for url (http://10.245.25.7/mail.delaage.fr-backups/config): error trying to connect: tcp connect error: No route to host (os error 113)
[WARN] operation=stat path=config -> retry after 8.774814248s: error=Unexpected (temporary) at stat, context: { url: http://10.245.25.7/mail.delaage.fr-backups/config, called: http_util::Client::send, service: s3, path: config } => send http request, source: error sending request for url (http://10.245.25.7/mail.delaage.fr-backups/config): error trying to connect: tcp connect error: No route to host (os error 113)
[WARN] operation=stat path=config -> retry after 16.142160177s: error=Unexpected (temporary) at stat, context: { url: http://10.245.25.7/mail.delaage.fr-backups/config, called: http_util::Client::send, service: s3, path: config } => send http request, source: error sending request for url (http://10.245.25.7/mail.delaage.fr-backups/config): error trying to connect: tcp connect error: No route to host (os error 113)
[ERROR] service=s3 operation=stat path=config -> Unexpected (persistent) at stat, context: { url: http://10.245.25.7/mail.delaage.fr-backups/config, called: http_util::Client::send, service: s3, path: config } => send http request, source: error sending request for url (http://10.245.25.7/mail.delaage.fr-backups/config): error trying to connect: tcp connect error: No route to host (os error 113)
error: error listing the repo config file
$ echo $?
0
```
I am using s3 storage using the OpenDAL backend and rustic version v0.7.0

**Comment by simonsan** [comment] 2024-07-29 15:52
Closing for being a duplicate of #927

**Closed by simonsan** 2024-07-29 15:52 UTC
Labels: S-triage
